# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bunkerApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Google/SignIn'

  # Pods for mobile

  target 'bunkerApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bunkerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
