const memes = [
	{value: "10g", label: "10 Guy"},
	{value: "1950mf", label: "1950S Middle Finger"},
	{value: "1990fwp", label: "1990S First World Problems"},
	{value: "aig", label: "Aaaaand Its Gone"},
	{value: "aam", label: "Actual Advice Mallard"},
	{value: "ad", label: "Advice Dog"},
	{value: "ag", label: "Advice God"},
	{value: "ay", label: "Advice Yoda"},
	{value: "att", label: "All The Things"},
	{value: "aa", label: "Ancient Aliens"},
	{value: "acgr", label: "Angry Chef Gordon Ramsay"},
	{value: "aw", label: "Angry Walter"},
	{value: "ap", label: "Annoyed Picard"},
	{value: "afg", label: "Annoying Facebook Girl"},
	{value: "ajc", label: "Anti Joke Chicken"},
	{value: "ayrf", label: "Aw Yeah Rage Face"},
	{value: "bg", label: "Baby Godfather"},
	{value: "bimd", label: "Back In My Day"},
	{value: "bje", label: "Bad Joke Eel"},
	{value: "blb", label: "Bad Luck Brian"},
	{value: "bsr", label: "Batman Slapping Robin"},
	{value: "beargrylls", label: "Bear Grylls"},
	{value: "bsy", label: "Beyonce Superbowl Yell"},
	{value: "bmg", label: "Bill Murray Golf"},
	{value: "bb", label: "Blackjack Bender"},
	{value: "bteq", label: "Boy That Escalated Quickly"},
	{value: "by", label: "Brace Yourselves"},
	{value: "bc", label: "Buddy Christ"},
	{value: "bte", label: "Buddy The Elf"},
	{value: "businesscat", label: "Business Cat"},
	{value: "bd", label: "Butthurt Dweller"},
	{value: "ch", label: "Captain Hindsight"},
	{value: "cpf", label: "Captain Picard Facepalm"},
	{value: "cgs", label: "Cereal Guy Spitting"},
	{value: "carf", label: "Challenge Accepted Rage Face"},
	{value: "chavez", label: "Chavez"},
	{value: "cgr", label: "Chef Gordon Ramsay"},
	{value: "cc", label: "Chemistry Cat"},
	{value: "cbg", label: "Chubby Bubbles Girl"},
	{value: "cf", label: "College Freshman"},
	{value: "cl", label: "College Liberal"},
	{value: "cg", label: "Computer Guy"},
	{value: "cgf", label: "Computer Guy Facepalm"},
	{value: "cw", label: "Condescending Wonka"},
	{value: "cb", label: "Confession Bear"},
	{value: "ck", label: "Confession Kid"},
	{value: "confusedlebowski", label: "Confused Lebowski"},
	{value: "conspiracykeanu", label: "Conspiracy Keanu"},
	{value: "consuela", label: "Consuela"},
	{value: "couragewolf", label: "Courage Wolf"},
	{value: "cboc", label: "Crying Because Of Cute"},
	{value: "cs", label: "Csi Sunglasses"},
	{value: "dsm", label: "Dating Site Murderer"},
	{value: "derp", label: "Derp"},
	{value: "derpina", label: "Derpina"},
	{value: "dg", label: "Disaster Girl"},
	{value: "dpd", label: "Dj Pauly D"},
	{value: "doge", label: "Doge"},
	{value: "ds", label: "Down Syndrome"},
	{value: "dr", label: "Downvoting Roman"},
	{value: "deq", label: "Dr Evil Quotes"},
	{value: "db", label: "Drunk Baby"},
	{value: "dwightschrute", label: "Dwight Schrute"},
	{value: "ep", label: "Engineering Professor"},
	{value: "ermahgerd", label: "Ermahgerd"},
	{value: "eb", label: "Ermahgerd Beyonce"},
	{value: "eltm", label: "Everyone Loses Their Minds"},
	{value: "eo", label: "Evil Otter"},
	{value: "epr", label: "Evil Plotting Raccoon"},
	{value: "et", label: "Evil Toddler"},
	{value: "fgp", label: "Family Guy Peter"},
	{value: "fdotik", label: "First Day On The Internet Kid"},
	{value: "fwp", label: "First World Problems"},
	{value: "fy", label: "Fk Yeah"},
	{value: "fa", label: "Forever Alone"},
	{value: "fbf", label: "Foul Bachelor Frog"},
	{value: "ff", label: "Futurama Fry"},
	{value: "fl", label: "Futurama Leela"},
	{value: "grf", label: "Gasp Rage Face"},
	{value: "gollum", label: "Gollum"},
	{value: "ggg", label: "Good Guy Greg"},
	{value: "greatguygreg", label: "Great Guy Greg"},
	{value: "gc", label: "Grumpy Cat"},
	{value: "hgrf", label: "Happy Guy Rage Face"},
	{value: "hj", label: "Heres Johnny"},
	{value: "hykhyw", label: "Hide Yo Kids Hide Yo Wife"},
	{value: "heaf", label: "High Expectations Asian Father"},
	{value: "ha", label: "Hipster Ariel"},
	{value: "hb", label: "Hipster Barista"},
	{value: "idwtlotpa", label: "I Dont Want To Live On This Planet Anymore"},
	{value: "isbabc", label: "I Should Buy A Boat Cat"},
	{value: "itltld", label: "I Too Like To Live Dangerously"},
	{value: "ing", label: "Idiot Nerd Girl"},
	{value: "iykwimb", label: "If You Know What I Mean Bean"},
	{value: "ihyk", label: "Ill Have You Know"},
	{value: "igo", label: "Impossibru Guy Original"},
	{value: "iw", label: "Insanity Wolf"},
	{value: "igs", label: "Internet Grandma Surprise"},
	{value: "ig", label: "Internet Guide"},
	{value: "ihm", label: "Irrationally Hostile Mark"},
	{value: "jcw", label: "Jackie Chan Wtf"},
	{value: "jd", label: "Joseph Ducreux"},
	{value: "kji", label: "Kim Jong Ill"},
	{value: "kjuf", label: "Kim Jong Un Frown"},
	{value: "kjugc", label: "Kim Jong Un Golf Clap"},
	{value: "kjus", label: "Kim Jong Un Salute"},
	{value: "kjuwdym", label: "Kim Jong Un What Do You Mean"},
	{value: "kjuwpc", label: "Kim Jong Un Whine Press Conference"},
	{value: "lpc", label: "Lame Pun Coon"},
	{value: "lmis", label: "Laughing Men In Suits"},
	{value: "lv", label: "Laughing Villains"},
	{value: "laundryviking", label: "Laundry Viking"},
	{value: "lcs", label: "Lazy College Senior"},
	{value: "lnt", label: "Liam Neeson Taken"},
	{value: "lyp", label: "Love You Puppy"},
	{value: "mam", label: "Malicious Advice Mallard"},
	{value: "mm", label: "Matrix Morpheus"},
	{value: "mmni", label: "Mckayla Maroney Not Impressed"},
	{value: "mrmackey", label: "Mr Mackey"},
	{value: "mo8g", label: "Musically Oblivious 8Th Grader"},
	{value: "ndt", label: "Neil Degrasse Tyson"},
	{value: "np", label: "No Patrick"},
	{value: "nbo", label: "Not Bad Obama"},
	{value: "osl", label: "Office Space Lumbergh"},
	{value: "ogrf", label: "Okay Guy Rage Face2"},
	{value: "ok", label: "Omg Karen"},
	{value: "odns", label: "One Does Not Simply"},
	{value: "oag", label: "Overly Attached Girlfriend"},
	{value: "omm", label: "Overly Manly Man"},
	{value: "pe", label: "Patriotic Eagle"},
	{value: "pfr", label: "Pepperidge Farm Remembers"},
	{value: "pgn", label: "Peter Griffin News"},
	{value: "philosoraptor", label: "Philosoraptor"},
	{value: "phteven", label: "Phteven"},
	{value: "poo", label: "Pissed Off Obama"},
	{value: "po", label: "Professor Oak"},
	{value: "pcb", label: "Ptsd Clarinet Boy"},
	{value: "pisep", label: "Put It Somewhere Else Patrick"},
	{value: "qrf", label: "Question Rage Face"},
	{value: "rb", label: "Rebecca Black"},
	{value: "rw", label: "Redditors Wife"},
	{value: "rt", label: "Resharper Tip"},
	{value: "ritc", label: "Right In The Childhood"},
	{value: "rs", label: "Ron Swanson"},
	{value: "rf", label: "Rpg Fan"},
	{value: "sadhamster", label: "Sad Hamster"},
	{value: "sjg", label: "Samuel Jackson Glance"},
	{value: "sf", label: "Schrute Facts"},
	{value: "sb", label: "Scumbag Brain"},
	{value: "sg", label: "Scumbag Girl"},
	{value: "sm", label: "Scumbag Minecraft"},
	{value: "ss", label: "Scumbag Steve"},
	{value: "sx", label: "Serious Xzibit"},
	{value: "seriouslyface", label: "Seriously Face"},
	{value: "ssm", label: "Sheltering Suburban Mom"},
	{value: "suatmmf", label: "Shut Up And Take My Money Fry"},
	{value: "skepticalbaby", label: "Skeptical Baby"},
	{value: "slowpoke", label: "Slowpoke"},
	{value: "snape", label: "Snape"},
	{value: "saap", label: "Socially Awesome Awkward Penguin"},
	{value: "sociallyawesomepenguin", label: "Socially Awesome Penguin"},
	{value: "sap", label: "Socially Awkward Penguin"},
	{value: "spc", label: "South Park Craig"},
	{value: "sl", label: "Sparta Leonidas"},
	{value: "scd", label: "Spiderman Computer Desk"},
	{value: "sh", label: "Spiderman Hospital"},
	{value: "spp", label: "Spiderman Peter Parker"},
	{value: "sk", label: "Success Kid"},
	{value: "sko", label: "Success Kid Original"},
	{value: "sbm", label: "Successful Black Man"},
	{value: "scc", label: "Sudden Clarity Clarence"},
	{value: "scsi", label: "Super Cool Ski Instructor"},
	{value: "surprisedkoala", label: "Surprised Koala"},
	{value: "tid", label: "Technologically Impaired Duck"},
	{value: "tb", label: "The Bobs"},
	{value: "tmimitw", label: "The Most Interesting Man In The World"},
	{value: "twsk", label: "Third World Skeptical Kid"},
	{value: "thirdworldsuccesskid", label: "Third World Success Kid"},
	{value: "tub", label: "Thumbs Up Boehner"},
	{value: "tdh", label: "Too Damn High"},
	{value: "tse", label: "Toy Story Everywhere"},
	{value: "ts", label: "True Story"},
	{value: "uhst", label: "Unhelpful High School Teacher"},
	{value: "vd", label: "Vengeance Dad"},
	{value: "wyii", label: "What Year Is It"},
	{value: "ws", label: "Whisper Sloth"},
	{value: "wci", label: "Why Cant I"},
	{value: "wnz", label: "Why Not Zoidberg"},
	{value: "yun", label: "Y U No"},
	{value: "ym", label: "Yao Ming"},
	{value: "ydhy", label: "Yo Dawg Heard You"},
	{value: "yds", label: "You Dont Say"},
	{value: "ysfbz", label: "You Should Feel Bad Zoidberg"}
];

module.exports = {
	getHelp() {
		const memeImageStringBuilder = [];
		for (var i = 0; i < memes.length; i += 2) {
			// first column
			var row = _.padEnd(`${memes[i].value} — ${memes[i].label}`, 60);

			// second column
			if (i + 1 < memes.length) {
				row += `${memes[i + 1].value} — ${memes[i + 1].label}`;
			}

			memeImageStringBuilder.push(row);
		}

		return `
Meme help
Format: /meme image text line 1 | text line 2

Available images:

${memeImageStringBuilder.join('&#10;')}
		`;
	}
};
